# CodeRabbit Configuration File
# Documentation: https://coderabbit.ai/docs/configure-coderabbit

version: "2"

language: "en-US"

# Review Settings
reviews:
  profile: "chill"  # Options: "chill", "assertive"
  request_changes_workflow: false
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
    base_branches: ["main"]

# Chat Settings
chat:
  auto_reply: true

# Knowledge Base (for context awareness)
knowledge_base:
  learnings: true
  issues: true
  pull_requests: true

# File Filters
# Exclude generated files, locks, and temporary artifacts from review
filters:
  excludes:
    - "uv.lock"
    - "poetry.lock"
    - "package-lock.json"
    - "yarn.lock"
    - "**/*.pyc"
    - "**/__pycache__/**"
    - "htmlcov/**"
    - ".coverage"
    - "dist/**"
    - "build/**"
    - "site/**"
    - ".idea/**"
    - ".vscode/**"
    - "mcp-server-mock/**"  # Mock server is for testing, less critical for deep review
